### History
HISTFILE="$HOME/.bash_history"
HISTSIZE=50000
HISTCONTROL=ignoredups:erasedups
shopt -s histappend
PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

### Completion
if [ -f /opt/homebrew/etc/profile.d/bash_completion.sh ]; then
  source /opt/homebrew/etc/profile.d/bash_completion.sh
elif [ -f /etc/bash_completion ]; then
  source /etc/bash_completion
fi

### Aliases
# Navigation
alias ls="eza"
alias ll="eza -l"
alias la="eza -la"
alias vi="nvim"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Development
alias nx="npx nx"
alias lg="lazygit"
alias ld="lazydocker"
alias dk="docker"
alias dkc="docker compose"
alias dke='docker compose exec $DKC_MAIN'
alias rlog="tail -f log/development.log"

# Git
alias gs="git status"
alias gc="git commit"
alias gp="git push"
alias gl="git pull"

### Prompt
BLUE="\[\033[0;34m\]"
RESET="\[\033[0m\]"
PS1=$BLUE'\W'" ${RESET}➜ "

### ENV
export EDITOR="hx"
export ICLOUD="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
export XDG_CONFIG_HOME="$HOME/.config"
export CLAUDE_CONFIG_DIR="$HOME/.config/claude"

### Path
export PATH="$HOME/.yarn/bin:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.config/yarn/global/node_modules/.bin:$HOME/.gem/ruby/3.3.0/bin:$HOME/configs/bin:$HOME/go/bin:$HOME/.local/bin:$HOME/.config/emacs/bin:$PATH"


### Homebrew
if command -v /opt/homebrew/bin/brew &> /dev/null; then
  export HOMEBREW_PREFIX="/opt/homebrew"
  export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
  export HOMEBREW_REPOSITORY="/opt/homebrew"
  export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:"
  export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}"

  export PATH="$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/sbin:$HOMEBREW_PREFIX/opt/libpq/bin:$HOMEBREW_PREFIX/opt/openssl@3/bin:$HOMEBREW_PREFIX/opt/curl/bin:$HOMEBREW_PREFIX/coreutils/libexec/gnubin:$PATH"
fi


### z
if [ -f /opt/homebrew/etc/profile.d/z.sh ]; then
  source /opt/homebrew/etc/profile.d/z.sh
fi

### direnv
if command -v direnv &>/dev/null; then
  eval "$(direnv hook bash)"
fi

### rbenv
if command -v rbenv &>/dev/null; then
  eval "$(rbenv init - bash)"
fi

### fzf
if command -v fzf &>/dev/null; then
  source <(fzf --bash)
fi

### Extra config
extra="$HOME/.extra.zsh"
if [[ -r "$extra" ]]; then
  source "$extra"
fi

# Added by Windsurf
export PATH="/Users/mbriggs/.codeium/windsurf/bin:$PATH"

