export EDITOR="nvim"
export ICLOUD="$HOME/Library/Mobile Documents/com~apple~CloudDocs"

### Path
path=(
    $HOME/.yarn/bin
    $HOME/.cargo/bin
    $HOME/.config/yarn/global/node_modules/.bin
    $path
    $HOME/go/bin
    $HOME/.local/bin
    $HOME/.config/emacs/bin
)

### Homebrew
if command -v /opt/homebrew/bin/brew &> /dev/null; then
    # from brew shellenv
    export HOMEBREW_PREFIX="/opt/homebrew";
    export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
    export HOMEBREW_REPOSITORY="/opt/homebrew";
    export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
    export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

    ### libpq
    export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/libpq/lib"
    export CPPFLAGS="$CPPFLAGS -I/opt/homebrew/opt/libpq/include"
    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/homebrew/opt/libpq/lib/pkgconfig"

    ### ruby
    export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/ruby/lib"
    export CPPFLAGS="$CPPFLAGS -I/opt/homebrew/opt/ruby/include"
    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/homebrew/opt/ruby/lib/pkgconfig"

    path=(
        $HOMEBREW_PREFIX/bin
        $HOMEBREW_PREFIX/sbin
        $HOMEBREW_PREFIX/opt/libpq/bin
        $HOMEBREW_PREFIX/opt/openssl@3/bin
        $HOMEBREW_PREFIX/opt/curl/bin
        $HOMEBREW_PREFIX/opt/ruby/bin
        $HOMEBREW_PREFIX/lib/ruby/gems/3.3.0/bin
        $HOMEBREW_PREFIX/coreutils/libexec/gnubin
        $path
        $HOMEBREW_PREFIX/opt/libpq/bin
    )
fi
