### libpq
export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/libpq/lib"
export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/ruby/lib"
export CPPFLAGS="$CPPFLAGS -I/opt/homebrew/opt/libpq/include"
export CPPFLAGS="$CPPFLAGS -I/opt/homebrew/opt/ruby/include"

export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/homebrew/opt/libpq/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/homebrew/opt/ruby/lib/pkgconfig"

### path

export BREW_PREFIX="/opt/homebrew"
export ICLOUD="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
export ZSH_THEME="powerlevel10k/powerlevel10k"
export EDITOR="nvim"
export GIT_PAGER="delta -s"

export path=(
	/usr/local/go/bin
	$BREW_PREFIX/bin
	$BREW_PREFIX/opt/libpq/bin
	$BREW_PREFIX/opt/openssl@3/bin
	$BREW_PREFIX/opt/ruby/bin
	$BREW_PREFIX/opt/curl/bin
	$BREW_PREFIX/opt/ruby/bin
  $BREW_PREFIX/lib/ruby/gems/3.3.0/bin
	$BREW_PREFIX/coreutils/libexec/gnubin
	$HOME/.yarn/bin
	$HOME/.cargo/bin
	$HOME/.config/yarn/global/node_modules/.bin
	$path
	$HOME/go/bin
	$HOME/.local/bin
	$HOME/.config/emacs/bin
	$BREW_PREFIX/opt/libpq/bin
)
. "$HOME/.cargo/env"
