### aliases
alias ls="eza"
alias vi="nvim"
alias nx="npx nx"
alias lg="lazygit"
alias ld="lazydocker"
alias dk="docker"
alias dkc="docker compose"
alias dke='docker compose exec $DKC_MAIN'
alias rlog="tail -f log/development.log"
alias aider='aider --model sonnet --anthropic-api-key "$(op read op://Private/Anthropic/credential --no-newline)"'



### p10k prompt

export ZSH_THEME="powerlevel10k/powerlevel10k"
p10k="$HOME/.local/share/powerlevel10k/powerlevel10k.zsh-theme"
if [ -f "$p10k" ]; then
	source "$p10k"
else
	echo "installing p10k..."
	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $(dirname "$p10k")
	source "$p10k"
fi

p10k_conf="$HOME/.config/p10k/p10k.zsh"
[[ ! -f "$p10k_conf" ]] || source "$p10k_conf"


### ENV
export EDITOR="nvim"
export ICLOUD="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
export XDG_CONFIG_HOME="$HOME/.config"


### Path
path=(
    $HOME/.yarn/bin
    $HOME/.cargo/bin
    $HOME/.config/yarn/global/node_modules/.bin
    $HOME/.gem/ruby/3.3.0/bin # needs to come before path because of macos stub for rails bin
    $path
    $HOME/configs/bin
    $HOME/go/bin
    $HOME/.local/bin
    $HOME/.config/emacs/bin
)

### Homebrew
if command -v /opt/homebrew/bin/brew &> /dev/null; then
    # from brew shellenv
    export HOMEBREW_PREFIX="/opt/homebrew";
    export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
    export HOMEBREW_REPOSITORY="/opt/homebrew";
    export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
    export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

    path=(
        $HOMEBREW_PREFIX/bin
        $HOMEBREW_PREFIX/sbin
        $HOMEBREW_PREFIX/opt/libpq/bin
        $HOMEBREW_PREFIX/opt/openssl@3/bin
        $HOMEBREW_PREFIX/opt/curl/bin
        $HOMEBREW_PREFIX/opt/ruby/bin
        $HOMEBREW_PREFIX/lib/ruby/gems/3.3.0/bin
        $HOMEBREW_PREFIX/coreutils/libexec/gnubin
        $path
        $HOMEBREW_PREFIX/opt/libpq/bin
    )
fi

### z

if [ -f /opt/homebrew/etc/profile.d/z.sh ]; then
	source /opt/homebrew/etc/profile.d/z.sh
fi

### direnv

if command -v direnv &>/dev/null; then
	eval "$(direnv hook zsh)"
fi

### rbenv
if command -v rbenv &>/dev/null;  then
  eval "$(rbenv init - --no-rehash zsh)"
fi

### fzf
if command -v fzf &>/dev/null;  then
  source <(fzf --zsh)
fi

### editing with nvim
autoload -Uz edit-command-line
zle -N edit-command-line

function kitty_scrollback_edit_command_line() { 
  local VISUAL='/Users/matt/.local/share/nvim/lazy/kitty-scrollback.nvim/scripts/edit_command_line.sh'
  zle edit-command-line
  zle kill-whole-line
}
zle -N kitty_scrollback_edit_command_line

bindkey '^x^e' kitty_scrollback_edit_command_line
