### aliases
alias ls="ls --color"
alias vi="nvim"
alias nx="npx nx"
alias lg="lazygit"
alias dk="docker"
alias dkc="docker compose"
alias dke='docker compose exec $DKC_MAIN'
alias rlog="tail -f log/development.log"

if [ -f /opt/homebrew/etc/profile.d/z.sh ]; then
	source /opt/homebrew/etc/profile.d/z.sh
fi

### direnv
if command -v direnv &>/dev/null; then
	eval "$(direnv hook zsh)"
fi

### p10k prompt
export ZSH_THEME="powerlevel10k/powerlevel10k"
p10k="$HOME/.local/share/powerlevel10k/powerlevel10k.zsh-theme"
if [ -f "$p10k" ]; then
	source "$p10k"
else
	echo "installing p10k..."
	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $(dirname "$p10k")
	source "$p10k"
fi

p10k_conf="$HOME/.config/p10k/p10k.zsh"
[[ ! -f "$p10k_conf" ]] || source "$p10k_conf"

### Always TMUX

# already in tmux
if [ -n "$TMUX" ]; then
  return
fi

# no tmux
if ! command -v tmux >/dev/null 2>&1; then
  return
fi

# Attempt to attach to the main session, or create it if it doesn't exist
if ! tmux has-session -t main 2>/dev/null; then
  tmux new-session -A -s main
else
  tmux attach -t main
fi

