start-at-login = true
accordion-padding = 20
automatically-unhide-macos-hidden-apps = true

# Handle breaking a tab off of a browser
[[on-window-detected]]
    if.app-id = 'com.brave.Browser'
    if.during-aerospace-startup = false
    check-further-callbacks = true
    run = 'layout tiling'           

# Email
[[on-window-detected]] # Spark
    if.app-id = 'com.readdle.SparkDesktop'
    if.during-aerospace-startup = false
    run = 'move-node-to-workspace E'

# Zoom (starting point)
[[on-window-detected]]
    if.app-id = 'us.zoom.xos'
    if.during-aerospace-startup = false
    run = 'move-node-to-workspace Z'

# Workspace U (Utility)
[[on-window-detected]] #1Password
    if.app-id = 'com.1password.1password'
    if.window-title-regex-substring = '— 1Password$'  # Match windows ending with "— 1Password"
    if.during-aerospace-startup = false
    run = 'move-node-to-workspace U'

[[on-window-detected]] # for 1Password Popups
    if.app-id = 'com.1password.1password'
    if.window-title-regex-substring = '^1Password$'
    if.during-aerospace-startup = false
    run = 'layout floating'

# Workspace M (Music)
[[on-window-detected]] # Music
    if.app-id = 'com.apple.Music'
    if.during-aerospace-startup = false
    run = 'move-node-to-workspace M'

# Workspace C (Chat)
[[on-window-detected]] # Slack
    if.app-id = 'com.tinyspeck.slackmacgap'
    if.during-aerospace-startup = false
    run = 'move-node-to-workspace C'

[[on-window-detected]] # Telegram
    if.app-id = 'ru.keepcoder.Telegram'
    if.during-aerospace-startup = false
    run = 'move-node-to-workspace C'

[[on-window-detected]] # Messages
    if.app-id = 'com.apple.MobileSMS'
    if.during-aerospace-startup = false
    run = 'move-node-to-workspace C'

# Workspace P (Planning)
[[on-window-detected]] # Notion Calendar
    if.app-id = 'com.cron.electron'
    if.during-aerospace-startup = false
    run = 'move-node-to-workspace P'

[[on-window-detected]] # Reminders
    if.app-id = 'com.apple.reminders'
    if.during-aerospace-startup = false
    run = 'move-node-to-workspace P'


[workspace-to-monitor-force-assignment]
P = ['built-in', 'secondary']

[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right
# All possible modifiers: cmd, alt, ctrl, shift
# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-period = 'fullscreen'

alt-tab = 'workspace-back-and-forth'
alt-backtick = 'focus-monitor --wrap-around next'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-semicolon = 'mode service'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-ctrl-1 = 'move-node-to-workspace 1'
alt-shift-1 = 'move-node-to-workspace --focus-follows-window 1'

alt-2 = 'workspace 2'
alt-ctrl-2 = 'move-node-to-workspace 2'
alt-shift-2 = 'move-node-to-workspace --focus-follows-window 2'

alt-3 = 'workspace 3'
alt-ctrl-3 = 'move-node-to-workspace 3'
alt-shift-3 = 'move-node-to-workspace --focus-follows-window 3'

alt-4 = 'workspace 4'
alt-ctrl-4 = 'move-node-to-workspace 4'
alt-shift-4 = 'move-node-to-workspace --focus-follows-window 4'

alt-5 = 'workspace 5'
alt-ctrl-5 = 'move-node-to-workspace 5'
alt-shift-5 = 'move-node-to-workspace --focus-follows-window 5'

alt-6 = 'workspace 6'
alt-ctrl-6 = 'move-node-to-workspace 6'
alt-shift-6 = 'move-node-to-workspace --focus-follows-window 6'

alt-7 = 'workspace 7'
alt-ctrl-7 = 'move-node-to-workspace 7'
alt-shift-7 = 'move-node-to-workspace --focus-follows-window 7'

alt-8 = 'workspace 8'
alt-ctrl-8 = 'move-node-to-workspace 8'
alt-shift-8 = 'move-node-to-workspace --focus-follows-window 8'

alt-9 = 'workspace 9'
alt-ctrl-9 = 'move-node-to-workspace 9'
alt-shift-9 = 'move-node-to-workspace --focus-follows-window 9'

alt-u = 'workspace U' # Utility
alt-ctrl-u = 'move-node-to-workspace U'
alt-shift-u = 'move-node-to-workspace --focus-follows-window U'

alt-e = 'workspace E' # Email
alt-ctrl-e = 'move-node-to-workspace E'
alt-shift-e = 'move-node-to-workspace --focus-follows-window E'

alt-z = 'workspace Z' # Zoom landing page
alt-ctrl-z = 'move-node-to-workspace Z'
alt-shift-z = 'move-node-to-workspace --focus-follows-window Z'

alt-c = 'workspace C' # Chat
alt-ctrl-c = 'move-node-to-workspace C'
alt-shift-c = 'move-node-to-workspace --focus-follows-window C'

alt-m = 'workspace M' # Music
alt-ctrl-m = 'move-node-to-workspace M'
alt-shift-m = 'move-node-to-workspace --focus-follows-window M'

alt-p = 'workspace P' # Planning
alt-ctrl-p = 'move-node-to-workspace P'
alt-shift-p = 'move-node-to-workspace --focus-follows-window P'


# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
b = ['balance-sizes', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']
