return {}
-- return {
-- 	"saghen/blink.cmp",
-- 	lazy = false,
-- 	version = "v0.*", -- REQUIRED release tag to download pre-built binaries
--
-- 	opts = {
-- 		-- experimental signature help support
-- 		trigger = { signature_help = { enabled = true } },
-- 		highlight = { use_nvim_cmp_as_default = true },
-- 		keymap = {
-- 			show = "<D-space>",
-- 			hide = "<S-CR>",
-- 			accept = "<C-y>",
-- 			select_next = { "<Tab>", "<Down>", "<C-n>" },
-- 			select_prev = { "<S-Tab>", "<Up>", "<C-p>" },
-- 			scroll_documentation_down = "<PageDown>",
-- 			scroll_documentation_up = "<PageUp>",
-- 		},
-- 		nerd_font_variant = "mono",
-- 	},
-- }
