theme = "tokyonight_moon"

[editor]
shell = ["/opt/homebrew/bin/bash", "-c"]
trim-trailing-whitespace = true

[editor.auto-save]
focus-lost = true


[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal]
# tab = :
tab = "command_mode"

# for macros, always use the q register. qq to record, Q to run
S-q = "@q"

# instead of home/end
S-h = "goto_line_start"
S-l = "goto_line_end"

# delete line
backspace = ["extend_to_line_bounds", "delete_selection"]

# select from cursor to line start/end
C-l = "extend_to_line_end"
C-h = "extend_to_line_start"

# more practical X
S-x = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.space]
# yazi instead of built in file explorer
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
