theme = "tokyonight_moon"

[editor]
shell = ["/opt/homebrew/bin/bash", "-c"]
trim-trailing-whitespace = true

[editor.auto-save]
focus-lost = true


[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal]
# ; = :
";" = "command_mode"

# for macros, always use the q register. qq to record, Q to run
S-q = "@q"

# instead of home/end
S-h = "goto_line_start"
S-l = "goto_line_end"

# more useful X
S-x = "extend_line_above"

 # select and jump to the next function via Treesitter
tab = "goto_next_function"

 # select and jump to the previous function via Treesitter
S-tab = "goto_prev_function"

# delete line
backspace = ["extend_to_line_bounds", "delete_selection"]

# select from cursor to line start/end
C-l = "extend_to_line_end"
C-h = "extend_to_line_start"

# make sure there is only one selection, select word under cursor, set search to selection, then switch to select mode
C-d = ["keep_primary_selection", "move_prev_word_start", "move_next_word_end", "search_selection", "select_mode"]

[keys.select]
# if already in select mode, just add new selection at next occurrence
C-d = ["search_selection", "extend_search_next"]

[keys.normal.ret]
# scooter support
s = [
    ":write-all",
    ":insert-output scooter >/dev/tty",
    ":redraw"
]

# lazygit support
g = [
    ":write-all",
    ":insert-output lazygit >/dev/tty",
    ":redraw"
]

# yazi support
y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
